services:
  front:
    build:
      context: ./front
    ports:
      - "19006:19006"
    volumes:
      - ./front:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npx expo start --tunnel --port 19006

  # ECS&MYSQL(EC2)で検証中
  # back:
  #   build: ./back
  #   ports:
  #     - "80:8080"
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/appdb
  #     - SPRING_DATASOURCE_USERNAME=appuser
  #     - SPRING_DATASOURCE_PASSWORD=apppass
  #   depends_on:
  #     - db

  # db:
  #   image: mysql:8.3
  #   restart: no
  #   environment:
  #     MYSQL_DATABASE: appdb
  #     MYSQL_USER: appuser
  #     MYSQL_PASSWORD: apppass
  #     MYSQL_ROOT_PASSWORD: rootpass
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql

volumes:
    db_data:
    node_modules:
